### ISSUE TITLE
Add related object to a newly created entity with ODataController and DataServiceContext

### ISSUE THREAD

**Issue by tfabian** [OData/odata.net#1518]
I would like to save a newly created entity with a newly created child in a single changeset (batch), with Microsoft.OData.Client 7.6.0 and Microsoft.AspNet.OData 7.1.0. The relationship between them is required: [dbo].[BoxInstance].[IdTemplateInstance] (FK, int, not null)
I've tried to call this:
```
var templateInstance = new TemplateInstance();
var boxInstance = new BoxInstance();

dataServiceContext.AddObject("TemplateInstances", templateInstance);
dataServiceContext.AddObject("BoxInstances", boxInstance);
dataServiceContext.AddLink(templateInstance, "BoxInstances", boxInstance);
```

This doesn't work because BoxInstance.IdTemplateInstance is 0 during the post, (ForeignKey violation).
My second attempt was to call AddRelatedObject:

```
dataServiceContext.AddObject("TemplateInstances", templateInstance);
dataServiceContext.AddRelatedObject(templateInstance, "BoxInstances", boxInstance);
dataServiceContext.SaveChangesAsync(SaveChangesOptions.BatchWithSingleChangeset);
```

In this case I receive the following error message:
_{"error":{"code":"","message":"No HTTP resource was found that matches the request URI 'http://localhost:41256/TemplateInstances(372)/BoxInstances'.","innererror":{"message":"No routing convention was found to select an action for the OData path with template '~/entityset/key/navigation'.","type":"","stacktrace":""}}}_

I have the following pocos and a ODataController:
```
  public class TemplateInstance : DomainEntity
  {
    public List<BoxInstance> BoxInstances { get; set; }
  }

  public class BoxInstance : DomainEntity
  {
    public TemplateInstance TemplateInstance { get; set; }
    public int IdTemplateInstance { get; set; }
  }

  //server side
  public class TemplateInstancesController : ODataController
  {
    [AcceptVerbs("POST", "PUT")]
    public IHttpActionResult CreateLink([FromODataUri]int key, string navigationProperty, [FromBody]Uri link)
    {
    }

    [AcceptVerbs("POST", "PUT")]
    public IHttpActionResult CreateRef(string navigationProperty, [FromBody] Uri link, ODataQueryOptions<TEntity> queryOptions)
    {
    }
  }
```

This is not a valid solution, because the first step can't be rolled back in case of failure of the second save changes:
```
dataServiceContext.Add(templateInstance);

dataServiceContext.SaveChanges();

boxInstance.IdTemplateInstance = templateInstance.Id;

dataServiceContext.Add(boxInstance);

dataServiceContext.SaveChanges();
```

Thanks!

**Comment by marabooy** [comment]
@tfabian Could you try this and let me know if it solves the issue you are experiencing. 
```
dataServiceContext.AddObject("TemplateInstances", templateInstance);
dataServiceContext.AddLink(templateInstance, "BoxInstances", boxInstance); //changed this from AddRelatedObject to AddLink
dataServiceContext.SaveChangesAsync(SaveChangesOptions.BatchWithSingleChangeset);
```
This should solve the issue you are experiencing as per the protocol definition for the [changesets](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398362)

**Comment by tfabian** [comment]
> @tfabian Could you try this and let me know if it solves the issue you are experiencing.
> 
> ```
> dataServiceContext.AddObject("TemplateInstances", templateInstance);
> dataServiceContext.AddLink(templateInstance, "BoxInstances", boxInstance); //changed this from AddRelatedObject to AddLink
> dataServiceContext.SaveChangesAsync(SaveChangesOptions.BatchWithSingleChangeset);
> ```
> 
> This should solve the issue you are experiencing as per the protocol definition for the [changesets](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398362)

**@marabooy** I have already tried this in the past. In this case the following exception has been thrown _System.InvalidOperationException: 'The context is not currently tracking the entity.'_
Both entities are newly created without Id, so I can't attach it to the context. I also tried to add it (AddObject) before calling AddLink, see my original post.

In the opposite direction it doesn't work neither:

```
      dataServiceContext.AddObject("BoxInstance", boxInstance);
      dataServiceContext.AddObject("TemplateInstances", templateInstance);
      dataServiceContext.SetLink(boxInstance, "TemplateInstance", templateInstance);
```

With this result:

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Scheme()
   at Microsoft.AspNet.OData.Batch.HttpRequestExtensions.CopyAbsoluteUrl(HttpRequest request, Uri uri)
   at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.ReadOperationInternalAsync(ODataBatchReader reader, HttpContext originalContext, Guid batchId, Nullable`1 changeSetId, CancellationToken cancellationToken, Boolean bufferContentStream)
   at Microsoft.AspNet.OData.Batch.ODataBatchReaderExtensions.ReadChangeSetRequestAsync(ODataBatchReader reader, HttpContext context, Guid batchId, CancellationToken cancellationToken)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ParseBatchRequestsAsync(HttpContext context)
   at Microsoft.AspNet.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
   at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS

Accept: multipart/mixed
Accept-Charset: UTF-8
Connection: Keep-Alive
Content-Length: 1761
Content-Type: multipart/mixed; boundary=batch_e0239049-e411-42ce-b6c1-fa372a953032
Host: localhost:44308
User-Agent: Microsoft.OData.Client/7.6.2
OData-Version: 4.0
OData-MaxVersion: 4.0

Thx

**Comment by marabooy** [comment]
@tfabian Could you share what the ID is for the two Models also could you share the properties in DomainEntity?

**Comment by tfabian** [comment]
```
using System.ComponentModel.DataAnnotations;
 
  [Microsoft.OData.Client.Key(nameof(Id))]
  public class DomainEntity : IEntity
  {
    [Key]
    public virtual int Id { get; set; }
  }

  public interface IEntity
  {
    int Id { get; set; }
  }
```

**Comment by marabooy** [comment]
@tfabian Thanks for the quick reply

**Comment by marabooy** [comment]
@tfabian Thank you for being patient. Just noticed in my earlier example I had not included the code to add the box instance so its tracked in DSC. I had missed the details in the stack trace you provided earlier. The correct code should have been.

```
dataServiceContext.AddObject("BoxInstances", boxInstance);
dataServiceContext.AddObject("TemplateInstances", templateInstance);
// this makes sure both objects are tracked in the context
dataServiceContext.AddLink(templateInstance, "BoxInstances", boxInstance); //this will create the batch request to call the TemplateController.CreateRef method

dataServiceContext.SaveChangesAsync(SaveChangesOptions.BatchWithSingleChangeset); 
```
Could you try this and let me know if this works. This should
The signature for my create ref method on the API is
 ```    [AcceptVerbs("POST", "PUT")]
        public async Task<IHttpActionResult> CreateRef([FromODataUri] int key, string navigationProperty, [FromBody] Uri link)
        ```

Tested with Microsoft.OData.Client 7.6.0 and Microsoft.AspNet.OData 7.1.0 and the latest versions and this works.

**Comment by marabooy** [comment]
For the approach below the controller needs to have an extra method to resolve the route
```
dataServiceContext.AddObject("TemplateInstances", templateInstance);
dataServiceContext.AddRelatedObject(templateInstance, "BoxInstances", boxInstance);
dataServiceContext.SaveChangesAsync(SaveChangesOptions.BatchWithSingleChangeset); 
```

Method signature for the route needed for the approach above to work 
``` 
        [AcceptVerbs("POST","PUT")]
        [ODataRoute("TemplateInstances({templateId})/BoxInstances")]
        public async Task<IHttpActionResult> AddBoxInstance([FromODataUri] int templateId, BoxInstance box)
        
```
This comes in handy for contained navigation

**Comment by tfabian** [comment]
Hi **@marabooy** ,
I tried the sample with AddLink, but it didn't work for me, the method CreateRef wasn't called. I recently moved to netcoreapp3.1 from net472. I'm testing it with Microsoft.OData.Client 7.6.2 (netcore WPF app)  and Microsoft.AspNetCore.OData 7.3.0.


Foreign key is not nullable.

DDL snippets:
```
CREATE TABLE [dbo].[BoxInstance](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdTemplateInstance] [int] NOT NULL);

ALTER TABLE [dbo].[TemplateInstance]  WITH CHECK ADD  CONSTRAINT [FkTemplateInstanceRelationship_3Template] FOREIGN KEY([IdTemplate])
REFERENCES [dbo].[Template] ([Id])

CREATE TABLE [dbo].[TemplateInstance](
	[Id] [int] IDENTITY(1,1) NOT NULL);

```

Thank you

**Comment by marabooy** [comment]
@tfabian The issue should be fixed in .net core version in this PR by @gathogojr  https://github.com/OData/WebApi/pull/2023 concerning the issue in .netcore libs
https://github.com/OData/odata.net/issues/1610. The client sends the right response but the server side version of .net core had a bug that's now fixed.

**Comment by marabooy** [comment]
@tfabian Closing this, Kindly do let us know if the fix in #1610 doesn't work so we can reopen.

**Comment by tfabian** [comment]
Please reopen this issue. I tried it with <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.4.0-Nightly202002252317" /> and it still doesn't work. 
I can confirm that Issue #1610 is solved, but this is another issue.

Thx

**Comment by marabooy** [comment]
Ok thanks for verifying this.

**Comment by tfabian** [comment]
[ODataIssue1518.zip](https://github.com/OData/odata.net/files/4268045/ODataIssue1518.zip)
I attached a simplistic solution in the zip file, will it be useful?

**Comment by marabooy** [comment]
@tfabian  Thanks for the sample. this helped alot. I will be transferring this issue to Odata\WebApi as this is an Issue in the batch reader in WebApi  [Batch reader:L127] for dotnet core (https://github.com/marabooy/WebApi/blob/master/src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs#L127) Which is [different](https://github.com/marabooy/WebApi/blob/master/src/Microsoft.AspNet.OData/Batch/ODataBatchReaderExtensions.cs#L152).
