### ISSUE TITLE
Support shortened key predicate of related entity

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#441]
Currently, the code logic is hard coded to `-2` to find a previous key segment:
https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs#L442

4.3.3 URLs for Related Entities with Referential Constraints
If a navigation property leading to a related entity type has a partner navigation property that specifies a referential constraint, then those key properties of the related entity that take part in the referential constraint MAY be omitted from URLs.
Example 21: full key predicate of related entity

https://host/service/Orders(1)/Items(OrderID=1,ItemNo=2)
Example 22: shortened key predicate of related entity

https://host/service/Orders(1)/Items(2)
The two above examples are equivalent if the navigation property Items from Order to OrderItem has a partner navigation property from OrderItem to Order with a referential constraint tying the value of the OrderID key property of the OrderItem to the value of the ID property of the Order.

The shorter form that does not specify the constrained key parts redundantly is preferred. If the value of the constrained key is redundantly specified then it MUST match the principal key value.
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398079

**Comment by lewischeng-ms** [comment]
Fixed in #442 

Plus some comments here:
 - How to build an entity type with two or more referential constraints? https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs#L471-L472
 - Now shortened URLs are supported. https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Microsoft.OData.Core.Tests/UriParser/ODataUriParserTests.cs#L423-L430

**Comment by JohanOtto** [comment]
Guys, this issue still happens with me when I have a class 

`[ForeignKey(nameof(ProjectId)+","+nameof(MilestoneId))]
    	
        public virtual ProjectMilestone ProjectMilestone { get; set; }`

This issue does not appear in version 5.3.1 which is currently my only work around. Can someone assist?

'The dependent property types 'System.Int32' are not same as the principal key types 'System.Int32,System.Int32'.
